version: "3.8"
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: "kumparan-postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=kumparan
    volumes:
      - kumparanDB:/var/lib/postgresql/data
  postgres-test:
    image: postgres:14.4-alpine
    container_name: "kumparan-postgres-test"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=kumparan-test
  backend:
    build:
      context: .
    container_name: "backend"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
volumes:
  kumparanDB: